# This is a basic workflow to help you get started with Actions

name: Cleanup Lists

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: [ master ]
    paths:
      - '**.list'
      - '**.txt'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  scan-duplicates:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Scan for duplicate lists
      run: |
        sh .github/workflows/scan-duplicates.sh

  verify-domains:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Ping All Hosts
        run: |
          sh .github/workflows/verify-domains.sh
